//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by snapit.rc
//
#define IDC_CLEAR                       3
#define IDC_SAVE                        4
#define IDS_APP_TITLE                   103
#define IDM_ABOUT                       104
#define IDS_THRESHOLD_ERROR             104
#define IDM_EXIT                        105
#define IDS_SELF                        105
#define IDS_OTHERS                      106
#define IDS_DESKTOP                     107
#define IDS_VCENTER                     108
#define IDI_SNAPIT                      109
#define IDS_HCENTER                     109
#define IDT_MYTRAY                      110
#define IDS_ENABLED                     110
#define IDS_PLAYSOUNDS                  111
#define IDS_UNSNAP_FILE                 112
#define IDS_BROWSE_UNSNAP               113
#define IDS_SNAP_FILE                   114
#define IDS_BROWSE_SNAP                 115
#define IDS_TOGGLEKEYS                  116
#define IDS_SCREEN_THRESH               117
#define IDS_WIN_THRESH                  118
#define IDS_SNAPTOL                     119
#define IDS_GENERALL                    120
#define IDS_SOUNDS                      121
#define IDS_SNAPMDI                     122
#define IDS_QUIETFAST                   123
#define IDS_INSIDES                     124
#define IDS_INVTOGGLE                   125
#define IDS_ADVL                        126
#define IDS_PLAY                        127
#define IDS_CROP_HINT                   128
#define IDC_SNAPIT                      129
#define IDS_HIDEICON                    130
#define IDS_KEPT                        131
#define IDS_CROP_TOP_HINT               132
#define IDR_SYSMENU                     133
#define IDS_CROP_RGN                    133
#define IDS_CROP_BOT_HINT               134
#define IDS_CHECK_HORIZONTAL            135
#define IDI_DISABLED                    136
#define IDS_CHECK_VERTICAL              136
#define IDD_ABOUT                       137
#define IDS_CROP_LEFT_HINT              137
#define IDS_CROP_RIGHT_HINT             138
#define IDI_SPEAKER                     143
#define IDI_SNAP_TOS                    144
#define IDD_GENERAL                     168
#define IDD_SOUNDS                      169
#define IDI_ENABLED                     170
#define IDR_WHAT                        200
#define IDM_WHAT                        201
#define IDI_PLAY                        208
#define IDD_ADVANCED                    211
#define IDI_TRAY_DISABLED_ARM64         214
#define IDI_TRAY_DISABLED_64            215
#define IDI_TRAY_ENABLED_32             217
#define IDM_DEBUG                       218
#define IDD_DEBUG                       219
#define IDD_GRID                        220
#define IDR_COPY                        228
#define IDI_TRAY_ENABLED_ARM64          231
#define IDI_TRAY_ENABLED_64             232
#define IDI_TRAY_DISABLED_32            235
#define IDC_WIN_THRESH                  1001
#define IDC_SCREEN_THRESH               1002
#define IDC_DESKTOP                     1013
#define IDC_SELF                        1014
#define IDC_OTHERS                      1015
#define IDC_ENABLED                     1016
#define IDC_HCENTER                     1017
#define IDC_VCENTER                     1018
#define IDC_PLAYSOUNDS                  1026
#define IDC_UNSNAP_FILE                 1029
#define IDC_BROWSE_UNSNAP               1030
#define IDC_SNAP_FILE                   1031
#define IDC_BROWSE_SNAP                 1032
#define IDC_TOGGLEKEYS                  1039
#define IDC_WIN_THRESH_SPIN             1047
#define IDC_SCREEN_THRESH_SPIN          1048
#define IDC_SNAPATL                     1049
#define IDC_PIXELSL                     1050
#define IDC_TOGGLEKEYL                  1051
#define IDC_GENERALL                    1052
#define IDC_SNAPATL2                    1053
#define IDC_SNAPFILEL                   1054
#define IDC_UNSNAPFILEL                 1055
#define IDC_CHOSEL                      1056
#define IDC_SOUNDSL                     1057
#define IDC_PIXELSL2                    1064
#define IDC_SNAPMDI                     1069
#define IDC_QUIETFAST                   1072
#define IDC_INSIDES                     1074
#define IDC_INVTOGGLE                   1075
#define IDC_ADVL                        1076
#define IDC_CROP_TOP                    1077
#define IDC_CROP_BOT                    1078
#define IDC_CROP_LEFT                   1079
#define IDC_HIDEICON                    1080
#define IDC_CROPTOPC                    1081
#define IDC_CROP_ENABLED                1081
#define IDC_CROP_RIGHT                  1082
#define IDC_KEPT                        1083
#define IDC_MSGLIST                     1084
#define IDC_CROP_RGN                    1085
#define IDC_CHECK_HORIZONTAL            1089
#define IDC_CHECK_VERTICAL              1090
#define IDC_RADIO_H_EVEN                1091
#define IDC_RADIO_H_PIXELS              1092
#define IDC_RADIO_H_SINGLE              1093
#define IDC_RADIO_V_EVEN                1094
#define IDC_RADIO_V_PIXELS              1095
#define IDC_RADIO_V_SINGLE              1096
#define IDC_H_NUM_EVEN                  1097
#define IDC_H_PIXELS_BTWN               1099
#define IDC_PLAY_SNAP                   1099
#define IDC_H_PIXELS_FROM_TOP           1100
#define IDC_PLAY_UNSNAP                 1100
#define IDC_V_NUM_EVEN                  1101
#define IDC_V_PIXELS_BTWN               1102
#define IDC_GROUP_CROP                  1102
#define IDC_V_PIXELS_FROM_LEFT          1103
#define IDC_CROP_TOP_SPIN               1104
#define IDC_CROP_BOT_SPIN               1105
#define IDC_CROP_LEFT_SPIN              1106
#define IDC_CROP_RIGHT_SPIN             1107
#define IDM_SETTINGS                    32772
#define IDS_ENABLED_TIP                 32774
#define IDS_DISABLED_TIP                32775
#define ID_ENABLEWINDOWSNAPPING         32776
#define IDM_COPY                        32785
#define ID_NOTHIN_COPY                  32787
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        236
#define _APS_NEXT_COMMAND_VALUE         32788
#define _APS_NEXT_CONTROL_VALUE         1105
#define _APS_NEXT_SYMED_VALUE           111
#endif
#endif
